// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkL2ymFuruPdTBFYrppFTeR5nVvUiXhvs',
    appId: '1:417547818643:web:72af52dd9447a5fc019f66',
    messagingSenderId: '417547818643',
    projectId: 'janlebar',
    authDomain: 'janlebar.firebaseapp.com',
    storageBucket: 'janlebar.appspot.com',
    measurementId: 'G-4BSZG7TZDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHtjDunPxm3Wr_C_EaGSOai72kH_IR1k',
    appId: '1:417547818643:android:62e7c4755ab7e04a019f66',
    messagingSenderId: '417547818643',
    projectId: 'janlebar',
    storageBucket: 'janlebar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNgf7UYGwSfPE8K-IuywaCcdG2-rghJDk',
    appId: '1:417547818643:ios:8fd3e124a863c533019f66',
    messagingSenderId: '417547818643',
    projectId: 'janlebar',
    storageBucket: 'janlebar.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNgf7UYGwSfPE8K-IuywaCcdG2-rghJDk',
    appId: '1:417547818643:ios:e0f16c90852a7529019f66',
    messagingSenderId: '417547818643',
    projectId: 'janlebar',
    storageBucket: 'janlebar.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
